apiVersion: v1
data:
  images.json: |-
    [
      "https://i.imgflip.com/7jmwe9.jpg",
      "https://i.imgflip.com/7jmwjs.jpg",
      "https://i.imgflip.com/7jmwqn.jpg",
      "https://i.imgflip.com/7jqekl.jpg",
      "https://i.imgflip.com/7jrt37.jpg",
      "https://i.imgflip.com/7jqevq.jpg",
      "https://www.photo-art.co.il/wp-content/uploads/2018/09/J75_5568-1.jpg"
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
